<a href="https://colab.research.google.com/github/txcagla/techcareer-assignments/blob/main/assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Soru 1 – Liste Metotları

Bir sınıfta öğrencilerin notları şu şekilde tutuluyor:

notlar = [85, 92, 76, 92, 100, 76, 85, 92]
- Listedeki tekrar eden notları silip benzersiz bir liste oluşturun.
- En yüksek ve en düşük notu bulun.
- Notları küçükten büyüğe sıralayın.

In [16]:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]

# benzersiz liste oluşturma
benzersiz_notlar = set(notlar)
print("benzersiz notlar: ", benzersiz_notlar)

# en yüksek ve en düşük notu bulma
en_yuksek = max(notlar)
en_dusuk = min(notlar)
print("en yüksek not: ", en_yuksek)
print("en düşük not: ", en_dusuk)

# küçükten büyüğe sıralama
sirali_notlar = sorted(notlar)
print("sıralı notlar: ", sirali_notlar)


benzersiz notlar:  {100, 92, 85, 76}
en yüksek not:  100
en düşük not:  76
sıralı notlar:  [76, 76, 85, 85, 92, 92, 92, 100]


Soru 2 – Sayılar

Bir sayının Armstrong sayısı olup olmadığını kontrol eden bir Python fonksiyonu yazın.

Armstrong sayısı: Her basamağının küplerinin toplamı kendisine eşit olan sayılar.

Örn: 153 → 1³+5³+3³ = 153

In [17]:
def is_armstrong(num):

    digits = str(num)

    sum = 0
    for digit in digits:
        sum += int(digit) ** 3

    if sum == num:
        return True
    else:
        return False

print(is_armstrong(153))

True


Soru 3 – Kümeler

Aşağıdaki iki küme verilmiştir:

A = {"Python", "R", "SQL", "Java"}

B = {"C++", "Python", "JavaScript", "SQL"}

- Ortak dilleri bulun.
- Sadece A’da olan dilleri listeleyin.
- İki kümenin birleşimini alfabetik olarak yazdırın.

In [18]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

# ortak dilleri yazdırma
common = A & B
print("ortak diller: ", common)

# sadece A kümesinde olan dilleri yazdırma
only_A = A - B
print("sadece A kümesinde olan diller: ", only_A)

# iki kümenin birleşimini yazdırma
sets_union = sorted(A | B)
print("iki kümenin alfabetik birleşimi: ", sets_union)


ortak diller:  {'Python', 'SQL'}
sadece A kümesinde olan diller:  {'R', 'Java'}
iki kümenin alfabetik birleşimi:  ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


Soru 4 – Modüller

- random modülünü kullanarak 1–100 arasında 10 rastgele sayı üretin.
- Bu sayıların ortalamasını ve standart sapmasını statistics modülü ile hesaplayın.

In [19]:
import random
import statistics

# 10 tane random sayı üretme
numbers = [random.randint(1, 100) for _ in range(10)]
print("random sayılar: ", numbers)

# ortalamayı hesaplama
mean_value = statistics.mean(numbers)
print("ortalama: ", mean_value)

# standart sapmayı hesaplama
std_dev = statistics.stdev(numbers)
print("standart sapma: ", std_dev)


random sayılar:  [85, 50, 9, 74, 46, 90, 74, 88, 19, 19]
ortalama:  55.4
standart sapma:  31.17762730620219


Soru 5 – Fonksiyonlar

kelime_sayacı(metin) adında bir fonksiyon yazın. Fonksiyon verilen metindeki:
- toplam kelime sayısını
- en uzun kelimeyi
- en sık geçen kelimeyi döndürsün.

In [20]:
from collections import Counter

def kelime_sayacı(metin):
    kelimeler = metin.split()

    # toplam kelime sayısı
    toplam_kelime = len(kelimeler)

    # en uzun kelime
    en_uzun_kelime = max(kelimeler, key=len)

    # en sık geçen kelime
    kelime_frekans = Counter(kelimeler)
    en_sik_kelime, frekans = kelime_frekans.most_common(1)[0]

    return toplam_kelime, en_uzun_kelime, en_sik_kelime

metin = "Bugün hava çok güzel ve bugün tüm gün dışarda olmak istiyorum"
sonuc = kelime_sayacı(metin)

print("toplam kelime sayısı: ", sonuc[0])
print("en uzun kelime: ", sonuc[1])
print("en sık geçen kelime: ", sonuc[2])


toplam kelime sayısı:  11
en uzun kelime:  istiyorum
en sık geçen kelime:  Bugün


Soru 6 – Gömülü Fonksiyonlar

Aşağıdaki liste için map, filter, sorted gibi gömülü fonksiyonları kullanarak:
sayilar = [5, 12, 7, 18, 24, 3, 16]
- Sadece çift sayıları filtreleyin.
- Bu sayıların karelerini bulun.
- Karelerini azalan sırada sıralayın.

In [21]:
nums = [5, 12, 7, 18, 24, 3, 16]

# çift sayıları filtrele
even_nums = list(filter(lambda x: x % 2 == 0, nums))

# karelerini bul
squares = list(map(lambda x: x ** 2, even_nums))

# azalan sırada sıralama
sorted_squares = sorted(squares, reverse=True)

print("çift sayılar:", even_nums)
print("kareleri:", squares)
print("azalan sırada kareler:", sorted_squares)


çift sayılar: [12, 18, 24, 16]
kareleri: [144, 324, 576, 256]
azalan sırada kareler: [576, 324, 256, 144]


Soru 7 – Lambda İfadeleri

Aşağıdaki listeyi, her kelimenin uzunluğuna göre küçükten büyüğe sıralayın.

kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]

Bunu sorted + lambda ile yapın.

In [22]:
words = ["veri", "bilim", "analiz", "yapayzeka", "python"]

sorted_words = sorted(words, key=lambda word: len(word))

print("sıralı kelimeler:", sorted_words)


sıralı kelimeler: ['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


Soru 8 – Metodlar


Bir string içinde geçen tüm rakamları bulun ve bunların toplamını döndüren bir fonksiyon yazın.

Örn: "abc12def3" → 12 + 3 = 15

In [23]:
def digit_sum(text):
    sum = 0
    number = ""

    for ch in text:
        if ch.isdigit():
            number += ch
        else:
            if number:
                sum += int(number)
                number = ""
    if number:
        sum += int(number)

    return sum

print(digit_sum("abc12def3"))


15


Soru 9 – (Ekstra) Numpy 1

10 elemanlı bir numpy dizisi oluşturun.
- Elemanlar 0–50 arasında rastgele sayılar olsun.
- Dizinin ortalamasını, standart sapmasını ve en büyük değerini bulun.

In [24]:
import numpy as np

arr = np.random.randint(0, 51, 10)
print("Array:", arr)

mean_value = np.mean(arr)
print("ortalama:", mean_value)

std_dev = np.std(arr)
print("standart sapma:", std_dev)

max_value = np.max(arr)
print("en büyük değer:", max_value)


Array: [ 5 42 48 26  5 21  1 31 16 21]
ortalama: 21.6
standart sapma: 14.927826365549677
en büyük değer: 48


Soru 10 – (Ekstra) Numpy 2

5x5 boyutunda rastgele 0–1 arasında değerlerden oluşan bir numpy matrisi üretin.
- Her sütunun ortalamasını bulun.
- 0.5’ten büyük olan değerleri 1, küçük eşit olanları 0 yaparak binary matris oluşturun.

In [25]:
import numpy as np

matrix = np.random.rand(5, 5)
print("Original Matrix:\n", matrix)

col_means = np.mean(matrix, axis=0)
print("\nColumn Means:", col_means)

binary_matrix = np.where(matrix > 0.5, 1, 0)
print("\nBinary Matrix:\n", binary_matrix)


Original Matrix:
 [[0.23915326 0.5569921  0.79414064 0.43278523 0.40604905]
 [0.66384843 0.97622322 0.69822294 0.6253177  0.44832366]
 [0.7196845  0.5148455  0.11628042 0.97590242 0.5488766 ]
 [0.05698112 0.27510699 0.62566253 0.42889361 0.75903629]
 [0.95475042 0.13919095 0.14592042 0.1812011  0.3423607 ]]

Column Means: [0.52688354 0.49247175 0.47604539 0.52882001 0.50092926]

Binary Matrix:
 [[0 1 1 0 0]
 [1 1 1 1 0]
 [1 1 0 1 1]
 [0 0 1 0 1]
 [1 0 0 0 0]]


Proje – “Kitap Satış Analiz Sistemi”

Bir yayınevinin farklı türlerde ve yazarlarda kitapları var. Örnek veri:

kitaplar = [
{"isim": "Veri Bilimi 101", "yazar": "Ali", "tur": "Bilim", "satis": 1200, "yil": 2021},

{"isim": "Python ile Yapay Zeka", "yazar": "Ayşe", "tur": "Bilim", "satis": 950, "yil": 2020},

{"isim": "İstatistik Temelleri", "yazar": "Ali", "tur": "Akademik", "satis": 700, "yil": 2019},

{"isim": "Makine Öğrenmesi", "yazar": "Can", "tur": "Bilim", "satis": 1800, "yil": 2022},

{"isim": "Veri Görselleştirme", "yazar": "Deniz", "tur": "Sanat", "satis": 400, "yil": 2018},

{"isim": "Matematiksel Modelleme", "yazar": "Ali", "tur": "Akademik", "satis": 1500, "yil": 2021},

{"isim": "Bilgi Toplumu", "yazar": "Ayşe", "tur": "Sosyal", "satis": 600, "yil": 2022}
]


Yapılması Gerekenler:
1. Fonksiyon Yazma:
- en_cok_satan(kitaplar) → En çok satan kitabın bilgilerini döndürsün.
- yazar_satislari(kitaplar) → Her yazarın toplam satışını bir sözlük olarak döndürsün.
2. Liste ve Küme İşlemleri:
- Tüm kitap türlerini (tur) küme halinde çıkarın (tekrar eden türler olmadan).
- Satış adedi 1000’den fazla olan kitapların isimlerini bir listede toplayın.
3. Lambda / Filter / Map Kullanımı:
- filter ile 2020’den sonra çıkan kitapları süzün.
- map ile tüm satış adetlerini %10 artırılmış şekilde yeni bir listeye aktarın.
- sorted + lambda ile kitapları satış miktarına göre azalan şekilde sıralayın.
4. İstatistiksel Analiz:
- Ortalama satış adedini bulun.
- En çok satış yapan türü bulun.
- Satışların standart sapmasını hesaplamak için statistics modülünü kullanın.
5. Ekstra (Zorlayıcı): Train/Test Simülasyonu
- Kitap listesini rastgele %70 eğitim (train), %30 test verisine ayırın (random.sample).
- Eğitim verisinden yazarların ortalama satışını hesaplayın.
- Test verisinde, hangi kitapların satışlarının bu ortalamanın üzerinde olduğunu kontrol edin.


Beklenen Çıktı Örneği
- En çok satan kitap: "Makine Öğrenmesi"
- Yazar satışları: {"Ali": 3400, "Ayşe": 1550, "Can": 1800, "Deniz": 400}
- Türler: {"Bilim", "Akademik", "Sanat", "Sosyal"}
- 1000’den fazla satan kitaplar: ["Veri Bilimi 101", "Makine Öğrenmesi", "Matematiksel Modelleme"]
- Ortalama satış: 1021.4
- Standart sapma: ~480.2


Eğitim/ Test ayırımı sonrası analiz:

Analizde Sizden Beklenen:
- Veriyi uygun oranlarda ayırın (örneğin %70 train, %30 test).
- Train seti üzerinde basit analizler yapın (ortalama, sıklık, vs.).
- Test seti üzerinde aynı analizleri tekrarlayın.
- Sonuçları karşılaştırın ve kısa yorum ekleyin.

In [26]:
import statistics
import random

# soruda sağlanan veriler
kitaplar = [
    {"isim": "Veri Bilimi 101", "yazar": "Ali", "tur": "Bilim", "satis": 1200, "yil": 2021},
    {"isim": "Python ile Yapay Zeka", "yazar": "Ayşe", "tur": "Bilim", "satis": 950, "yil": 2020},
    {"isim": "İstatistik Temelleri", "yazar": "Ali", "tur": "Akademik", "satis": 700, "yil": 2019},
    {"isim": "Makine Öğrenmesi", "yazar": "Can", "tur": "Bilim", "satis": 1800, "yil": 2022},
    {"isim": "Veri Görselleştirme", "yazar": "Deniz", "tur": "Sanat", "satis": 400, "yil": 2018},
    {"isim": "Matematiksel Modelleme", "yazar": "Ali", "tur": "Akademik", "satis": 1500, "yil": 2021},
    {"isim": "Bilgi Toplumu", "yazar": "Ayşe", "tur": "Sosyal", "satis": 600, "yil": 2022}
]

# 1. İstenen Fonksiyonları Oluşturma

def en_cok_satan(kitaplar):
    return max(kitaplar, key=lambda x: x["satis"])

def yazar_satislari(kitaplar):
    satislar = {}
    for k in kitaplar:
        satislar[k["yazar"]] = satislar.get(k["yazar"], 0) + k["satis"]
    return satislar

print("En çok satan kitap:", en_cok_satan(kitaplar)["isim"])
print("Yazar satışları:", yazar_satislari(kitaplar))


# 2. Liste ve Küme İşlemleri

turler = {k["tur"] for k in kitaplar}
bin_ustu = [k["isim"] for k in kitaplar if k["satis"] > 1000]

print("Türler:", turler)
print("1000’den fazla satan kitaplar:", bin_ustu)


# 3. Lambda, Filter, Map İşlemleri

# 2020’den sonra çıkan kitaplar
sonrasi_2020 = list(filter(lambda k: k["yil"] > 2020, kitaplar))

# Satışları %10 artırma
artisli_satislar = list(map(lambda k: k["satis"] * 1.1, kitaplar))

# Satışa göre azalan sıralama
sirali = sorted(kitaplar, key=lambda k: k["satis"], reverse=True)

print("2020 sonrası çıkan kitaplar:", [k["isim"] for k in sonrasi_2020])
print("Satışların %10 artırılmış hali:", artisli_satislar)
print("Satışa göre sıralama:", [k["isim"] for k in sirali])


# 4. İstatistiksel Analiz

satislar = [k["satis"] for k in kitaplar]

ortalama = statistics.mean(satislar)
std_sapma = statistics.stdev(satislar)

# En çok satış yapan tür
tur_satislari = {}
for k in kitaplar:
    tur_satislari[k["tur"]] = tur_satislari.get(k["tur"], 0) + k["satis"]

en_cok_tur = max(tur_satislari, key=tur_satislari.get)

print("Ortalama satış:", ortalama)
print("Standart sapma:", std_sapma)
print("En çok satış yapan tür:", en_cok_tur)


# 5. Train/Test Simülasyonu

# %70 eğitim, %30 test olarak ayırma
train_size = int(len(kitaplar) * 0.7)
train = random.sample(kitaplar, train_size)
test = [k for k in kitaplar if k not in train]

# Eğitim seti: yazarların ortalama satışları
train_satislar = [k["satis"] for k in train]
train_ortalama = statistics.mean(train_satislar)

print("\n--- Train/Test Analizi ---")
print("Train set kitapları:", [k["isim"] for k in train])
print("Test set kitapları:", [k["isim"] for k in test])
print("Train ortalama satış:", train_ortalama)

# Test setinde ortalamanın üzerinde satış yapanlar
ustunde = [k["isim"] for k in test if k["satis"] > train_ortalama]
print("Test setinde ortalamanın üzerinde olanlar:", ustunde)


En çok satan kitap: Makine Öğrenmesi
Yazar satışları: {'Ali': 3400, 'Ayşe': 1550, 'Can': 1800, 'Deniz': 400}
Türler: {'Sanat', 'Akademik', 'Bilim', 'Sosyal'}
1000’den fazla satan kitaplar: ['Veri Bilimi 101', 'Makine Öğrenmesi', 'Matematiksel Modelleme']
2020 sonrası çıkan kitaplar: ['Veri Bilimi 101', 'Makine Öğrenmesi', 'Matematiksel Modelleme', 'Bilgi Toplumu']
Satışların %10 artırılmış hali: [1320.0, 1045.0, 770.0000000000001, 1980.0000000000002, 440.00000000000006, 1650.0000000000002, 660.0]
Satışa göre sıralama: ['Makine Öğrenmesi', 'Matematiksel Modelleme', 'Veri Bilimi 101', 'Python ile Yapay Zeka', 'İstatistik Temelleri', 'Bilgi Toplumu', 'Veri Görselleştirme']
Ortalama satış: 1021.4285714285714
Standart sapma: 506.5053001179939
En çok satış yapan tür: Bilim

--- Train/Test Analizi ---
Train set kitapları: ['Python ile Yapay Zeka', 'Matematiksel Modelleme', 'Bilgi Toplumu', 'Veri Görselleştirme']
Test set kitapları: ['Veri Bilimi 101', 'İstatistik Temelleri', 'Makine Öğrenmesi